### ISSUE TITLE
Fix the crashing

### ISSUE THREAD

**Issue by buresdv** [buresdv/Mlem#50]
https://drive.google.com/file/d/1tRf8_yrl8hVReBb0SPm1DRKEFQy8_l-N/view?usp=share_link

Mostly has to do with this function: https://github.com/buresdv/Mlem/blob/master/Mlem/Logic/Networking/Infinite%20Loader.swift

**Comment by mormaer** [comment]
I'll aim to put a PR up tomorrow for this, looking at the crash reports I can see this:
```
Thread 3 Crashed:
0   Mlem                          	0x00000001000a1f14 Swift runtime failure: Unexpectedly found nil while unwrapping an Optional value + 0 (<compiler-generated>:0)
1   Mlem                          	0x00000001000a1f14 getCorrectURLtoEndpoint(baseInstanceAddress:) + 1580 (Get Correct URL to Endpoint.swift:20)
...
```

This suggests the crash is happening while executing `getCorrectURLtoEndpoint`, inside that function the possible endpoints are defined with `!` to force the creation of the URLs, that means if the value fed in as `baseInstanceAddress` is for any reason not representable as a `URL` it would crash.

I'll refactor it so that we early return and throw an error if we can't create the URLs.

Hopefully this will resolve it 🙏
